[PHP]
display_errors = Off
log_errors = On
expose_php = Off
extension_dir = "__COFFEEPOS_PHP_EXT_DIR__"
date.timezone = UTC

extension=curl
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=zip
